.\"
.TH SYSTEMSTATS 8 "16 NOV 2021" "0.3" "SYSTEMSTATS man page"
.\" -------------------------------------------------------------
.\" -------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -------------------------------------------------------------
.\" * MAIN CONTENTS START HERE *
.\" -------------------------------------------------------------
.SH NAME
systemstats \- retrieves information form host system
.SH SYNOPSIS
.HP \w'\fRsystemStats\fR\ 'u
\fRsystemStats\fR [\-c\ \fIcpu usage\fR] [\-i\ \fIIP address\fR] [\-t\ \fITemperature\fR]
.br

.SH DESCRIPTION
.PP
\fB\-c\fR
.RS
	show current CPU usage Free=##.##\% Used=##.##\%
.RE
.PP
\fB\-i\fR
.RS
	show hosts IPv4 address
.RE
.PP
\fB\-t\fR
.RS
	show current temperature of CPU temp=## C
.RE

.SH NOTES
This script will be developed over time to display more information using different options.

.SH AUTHORS
Chris Halsall <ch6941r@gre.ac.uk>
